name: Production Deployment

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})
    - name: replace test
      run: sed -i s/___AGENT_VERSION___/$RELEASE_VERSION/g monitornator.py
    - name: copy file via ssh
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.PRODUCTION_HOST }}
        USERNAME: ${{ secrets.PRODUCTION_USERNAME }}
        PORT: ${{ secrets.PRODUCTION_PORT }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source: "install.sh,monitornator.py"
        target: /home/${{ secrets.PRODUCTION_USERNAME }}/agent
